### ISSUE TITLE
the rkmessage->partition of a delivery report callback is not the correct one

### ISSUE THREAD

**Issue by nicolive83** [confluentinc/librdkafka#4246] opened 2023-04-07 10:46 UTC
Description
===========
The rkmessage->partition value is not the real one just sent, but is the previous one
This rkmessage is part of the delivery report callback set by the rd_kafka_conf_set_dr_msg_cb(conf, dr_msg_cb) function.

And the delivery report callback is never called on first message.

How to reproduce
================
Created a new topic with 10 partitions using:
bin/kafka-topics.sh --create   --topic quickstart-events --bootstrap-server localhost:9092 --partitions 10

Use the producer.c example to send input messages.

Start a listener on such topic:
bin/kafka-console-consumer.sh --topic quickstart-events --bootstrap-server localhost:9092 --property print.offset=true --property print.timestamp=true --property print.partition=true --property print.key=true

Start the produce to publish some messages:
% Type some text and hit enter to produce message
% Or just hit enter to only serve delivery reports
% Press Ctrl-C or Ctrl-D to exit
a
% Enqueued message (1 bytes) for topic quickstart-events
b
% Enqueued message (1 bytes) for topic quickstart-events
% Message delivered (1 bytes, **partition 9**)
c
% Enqueued message (1 bytes) for topic quickstart-events
% Message delivered (1 bytes, **partition 2**)
d
% Enqueued message (1 bytes) for topic quickstart-events
% Message delivered (1 bytes, **partition 2**)

=> Yet on listener side (also with consumer.c):
CreateTime:1680863322102        **Partition:9**     Offset:9        null    a
CreateTime:1680863326350        **Partition:2**     Offset:11       null    b
CreateTime:1680863331200        **Partition:2**     Offset:12       null    c
CreateTime:1680863337486        **Partition:3**     Offset:12       null    d

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
librdkafka-2.0.2
kafka_2.13-3.3.1
linux RH 

 - [x] librdkafka version (release number or git tag): librdkafka-2.0.2
 - [ x] Apache Kafka version: kafka_2.13-3.3.1
 - [x ] librdkafka client configuration: attached zip 
 - [x ] Operating system: Linux rousxl1005.rou.st.com 3.10.0-1160.53.1.el7.x86_64
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

[server.zip](https://github.com/confluentinc/librdkafka/files/11178279/server.zip)

**Comment by emasab** [comment] 2023-05-16 14:09
That isn't a bug, the example is polling only when `fgets` returns a line an given the non blocking poll only when next message is send the delivery report is processed. I've changed those producer examples a bit to make it clear.

**Comment by nhaq-confluent** [comment] 2024-02-06 23:30
Marking this as closed due to expected behaviour

**Closed by nhaq-confluent** 2024-02-06 23:30 UTC
Labels: expected behavior
